services:
    db:
        container_name: db
        image: postgres
        ports:
        - "5432:5432"
        volumes:
        - db_data:/var/lib/postgresql/data
        env_file:
        - .env.db

    backend:
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - ./socialnetwork/media:/app/socialnetwork/media  # Store images persistently
        - ./backend:/app  # Ensures backend code is available inside container
        ports:
        - "8000:8000"
        depends_on:
        - db
        env_file:
        - .env

    frontend:
        build: ./frontend
        command: npm start
        ports:
        - "3000:3000"
        volumes:
        - ./frontend:/app
        depends_on:
        - backend

volumes:
    db_data:
    media:  # Persistent storage for images