# Generated by Django 5.1.5 on 2025-02-12 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='socialnetwork.user')),
                ('friends', models.ManyToManyField(blank=True, to='socialnetwork.user')),
            ],
        ),
    ]
