# Generated by Django 5.1.5 on 2025-03-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.TextField(default='comment', editable=False),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='type',
            field=models.TextField(default='follow', editable=False),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.TextField(default='like', editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.TextField(default='post', editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(default='author', editable=False),
        ),
    ]
