# Generated by Django 5.1.5 on 2025-03-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
