# Generated by Django 5.1.5 on 2025-03-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='is_my_node',
            field=models.BooleanField(default=False),
        ),
    ]
