# Generated by Django 5.1.5 on 2025-03-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_remotenode_is_my_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remote_fqid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
