# Generated by Django 5.1.5 on 2025-02-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
