# Generated by Django 5.1.5 on 2025-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_user_remote_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remote_fqid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
