# Generated by Django 5.1.5 on 2025-02-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_alter_user_options_alter_user_managers_and_more'),
        ('socialnetwork', '0005_delete_comment'),
    ]

    operations = [
    ]
