# Generated by Django 5.1.5 on 2025-03-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_rename_content_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
    ]
