# Generated by Django 5.1.5 on 2025-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_rename_content_type_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.TextField(default='like', editable=False),
        ),
    ]
