# Generated by Django 5.1.5 on 2025-02-18 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 21, 36, 27, 84510, tzinfo=datetime.timezone.utc)),
        ),
    ]
