# Generated by Django 5.1.5 on 2025-02-18 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0010_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 22, 21, 58, 682294, tzinfo=datetime.timezone.utc)),
        ),
    ]
