# Generated by Django 5.1.5 on 2025-03-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_alter_post_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='published',
        ),
    ]
