# Generated by Django 5.1.5 on 2025-02-19 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 14, 24, 50, 353124, tzinfo=datetime.timezone.utc)),
        ),
    ]
