# Generated by Django 5.1.5 on 2025-02-19 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0013_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 0, 15, 50, 639440, tzinfo=datetime.timezone.utc)),
        ),
    ]
