# Generated by Django 5.1.5 on 2025-02-20 22:35

import socialnetwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0020_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=socialnetwork.models.user_profile_picture_path),
        ),
    ]
