# Generated by Django 5.1.5 on 2025-02-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0021_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends-only', 'Friends Only'), ('unlisted', 'Unlisted')], default='public', max_length=20),
        ),
    ]
