# Generated by Django 5.1.5 on 2025-02-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0022_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends-only', 'Friends Only'), ('unlisted', 'Unlisted'), ('deleted', 'Deleted')], default='public', max_length=20),
        ),
    ]
