# Generated by Django 5.1.5 on 2025-03-07 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0026_environmentsetting_user_is_approved'),
        ('socialnetwork', '0027_alter_like_post_commentlike'),
    ]

    operations = [
    ]
