# Generated by Django 5.1.5 on 2025-03-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0028_environmentsetting_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_etag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
