# Generated by Django 5.1.5 on 2025-03-20 21:05

import socialnetwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0029_user_github_user_github_etag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to=socialnetwork.models.user_profile_picture_path),
        ),
    ]
