# Generated by Django 5.1.5 on 2025-03-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0026_friendship'),
        ('socialnetwork', '0029_user_github_user_github_etag'),
    ]

    operations = [
    ]
