# Generated by Django 5.1.5 on 2025-03-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0030_alter_user_profile_picture'),
        ('socialnetwork', '0030_remotenode'),
    ]

    operations = [
    ]
