# Generated by Django 5.1.5 on 2025-03-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0031_comment_type_followrequest_type_like_type_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='type',
            field=models.TextField(default='comment_like', editable=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.TextField(default='post_like', editable=False),
        ),
    ]
