# Generated by Django 5.1.5 on 2025-02-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
